# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "skggm"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  skggm: Gaussian graphical models for scikit-learn.
  Can put additional blurb here.
baseurl: "/skggm" # the subpath of your site, e.g. /blog
url: "https://jasonlaska.github.io/skggm" # "" the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

authors:
  Jason:
    name: Jason Laska
    display_name: Jason
    # gravatar: c66919cb194f96c696c1da0c47354a6a
    email: jlaska@gmail.com
    web: http://company.com
    twitter: chappaquack
    github: jasonlaska
  Manjari:
    name: Manjari Narayan
    display_name: Manjari
    # gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: TODO@company.com
    web: http://company.com
    twitter: TODO
    github: mnarayan


# Build settings
markdown: kramdown
theme: minima 

# gems: ['jekyll-github-metadata']